name: Pull actions

on:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@v5"

        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"
            ignore: brands

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
        - uses: "actions/checkout@v5"
        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "0.7"
            enable-cache: true
        - name: "Set up Python"
          uses: actions/setup-python@v6
          with:
            python-version-file: ".python-version"
        - name: Install the project
          run: uv sync --locked --all-extras --dev
        - name: Run ruff
          run: uv run ruff check

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v5"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: |
          uv run pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            --cov custom_components.ta_cmi \
            --asyncio-mode=auto \
            -o console_output_style=count \
            -p no:sugar \
            tests
